export const LEGACY_BEERS = [
  {
    name: "Golden Hour Pilsner",
    style: "German Pilsner",
    abv: 4.8,
    ibu: 32,
    srm: 3,
    fillGlass: "pilsner_flute",
    fraction: 0.93,
  },
  {
    name: "Cloudline IPA",
    style: "Hazy IPA",
    abv: 6.4,
    ibu: 45,
    srm: 5,
    fillGlass: "ipa_glass",
    fraction: 0.78,
  },
  {
    name: "Copper Trail Amber",
    style: "American Amber Ale",
    abv: 5.3,
    ibu: 30,
    srm: 14,
    fillGlass: "nonic_pint",
    fraction: 0.6,
  },
  {
    name: "Midnight Porter",
    style: "Robust Porter",
    abv: 5.8,
    ibu: 35,
    srm: 32,
    fillGlass: "stout_glass",
    fraction: 0.43,
  },
  {
    name: "Orchard Saison",
    style: "Saison",
    abv: 6.1,
    ibu: 25,
    srm: 5,
    fillGlass: "tulip_glass",
    fraction: 0.27,
  },
  {
    name: "Summer Wheat",
    style: "Hefeweizen",
    abv: 5.0,
    ibu: 12,
    srm: 4,
    fillGlass: "wheat_glass",
    fraction: 0.12,
  },
] as const;

export const LEGACY_ON_DECK = {
  name: "Harvest Märzen",
  beverageType: "beer",
  style: "Märzen",
  abv: 5.7,
  ibu: 24,
  srm: 12,
  fg: 1.013,
  fillGlass: "mug",
  description: "Fictional sample beer waiting On Deck in Simulation.",
} as const;
