export {
  canonicalizeJson,
  computeSemanticPayloadDigest,
  isValidClientSampleId,
  normalizeExternalTelemetrySample,
  parseRfc3339Timestamp,
  type MassUnit,
  type NormalizedTelemetrySample,
  type TemperatureUnit,
  type VolumeUnit,
} from "./normalization.ts";
export { TELEMETRY_NORMALIZATION_VERSION } from "./types.ts";
export { InMemoryTelemetryRateLimiter } from "./rate-limiter.ts";
export {
  deleteTapTelemetryAuthority,
  insertTelemetryMeasurement,
  insertTelemetryReceipt,
  insertTelemetrySource,
  listAllSourceTapStatuses,
  listSourceTapStatusesForTap,
  listTapTelemetryAuthorities,
  listTelemetrySources,
  listTelemetrySourcesWithKeyDetails,
  TELEMETRY_PRUNE_BATCH_SIZE,
  pruneMeasurementsOlderThan,
  pruneReceiptsOlderThan,
  readMeasurementById,
  readReceiptByClientSampleId,
  readReceiptByFallbackIdentity,
  readSourceTapStatus,
  readTapTelemetryAuthority,
  readTelemetrySettings,
  readTelemetrySourceByCurrentMachineKeyId,
  readTelemetrySourceById,
  readTelemetrySourceByName,
  updateTelemetrySettings,
  updateTelemetrySourceCurrentMachineKey,
  updateTelemetrySourceName,
  upsertSourceTapStatus,
  upsertTapTelemetryAuthority,
} from "./repository.ts";
export { registerTelemetryRoutes, type TelemetryRouteDependencies } from "./routes.ts";
export {
  validateDetectorArbitrationGroupCreate,
  validateDetectorArbitrationGroupPatch,
  validateCompleteDetectorConfig,
  validateDetectorGroupId,
  validateDetectorTapOverridePatch,
  validateEmptyOptionalBody,
  validateGlobalDetectorConfigPatch,
} from "./detector-validation.ts";
export { TelemetryService, type TelemetryServiceDependencies } from "./service.ts";
export {
  validateAssignAuthorityInput,
  validateBatchTelemetryPayload,
  validateCreateTelemetrySourceInput,
  validateExternalBatchTelemetryPayload,
  validateExternalTelemetryPayload,
  mapExternalBatchTelemetryPayloadToInternal,
  mapExternalTelemetryPayloadToInternal,
  validateRenameTelemetrySourceInput,
  validateRotateTelemetrySourceInput,
  validateSingleTelemetryPayload,
  validateTapId,
  validateTapNumber,
  validateTelemetrySourceId,
  validateUpdateTelemetrySettingsInput,
} from "./telemetry-validation.ts";
export type {
  AcceptedSampleEvent,
  AcceptedTelemetryExtensionPort,
  AssignAuthorityInput,
  AuthorityChangedEvent,
  BatchIngestResult,
  BatchItemIngestResult,
  CreateTelemetrySourceInput,
  ExternalBatchTelemetryInput,
  ExternalBatchTelemetrySampleInput,
  ExternalBatchTelemetryRequestInput,
  ExternalBatchTelemetryRequestSampleInput,
  ExternalTelemetryMeasurementInput,
  ExternalTelemetryRequestInput,
  ExternalTelemetryTemperatureInput,
  ExternalTelemetrySampleInput,
  RenameTelemetrySourceInput,
  RotateTelemetrySourceInput,
  SingleIngestResult,
  TapTelemetryAuthority,
  TapTelemetryAuthorityRow,
  TelemetryAuthorityExtensionPort,
  TelemetryIngestReceipt,
  TelemetryIngestReceiptRow,
  TelemetryMeasurement,
  TelemetryMeasurementRow,
  TelemetryRateLimiter,
  TelemetrySettings,
  TelemetrySettingsRow,
  TelemetrySource,
  TelemetrySourceRow,
  TelemetrySourceTapStatus,
  TelemetrySourceTapStatusRow,
  TelemetrySourceWithKeyDetails,
  TelemetrySourceWithKeyRow,
  UpdateTelemetrySettingsInput,
} from "./types.ts";
